name: Gallantry GRID
favicon: null
layout_spectrum: 0.22172450949437916
typography_spectrum: 0.5250901144463569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a36c36'
    - '#4b2558'
    - '#401035'
    - '#784b45'
    - '#6d3a1d'
  brandStrength: 0.9482337045483291
  lightness: 0.09707144019193947
  saturation: 0.625
  rhythmicContrast: 0.07356418808922172
purpose: []
