name: Gallantry GRID
favicon: null
layout_spectrum: 0.49959
typography_spectrum: 0.48444
title: Gallantry GRID
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a36c36'
    - '#4b2558'
    - '#401035'
    - '#784b45'
    - '#6d3a1d'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
