name: Gallantry GRID
favicon: null
layout_spectrum: 0.22172450949437916
typography_spectrum: 0.5250901144463569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9482337045483291
  lightness: 0.09707144019193947
  saturation: 0.8629275963176042
  rhythmicContrast: 0.07356418808922172
purpose: []
